# Generated by Django 2.2.12 on 2021-04-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeesdetail',
            name='branch_choose',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('ME', 'Mechanical Engineering'), ('CE', 'Computer Engineering'), ('ENTC', 'Electronic Engineering'), ('AE', 'Aerospace Engineering'), ('Chem E', 'Chemical Engineering'), ('Civil E', 'Civil Engineeing')], default='Computer Engineering', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentfeesdetail',
            name='engineering_year',
            field=models.CharField(choices=[('FY', 'FIRST YEAR'), ('SY', 'SECOND YEAR'), ('TY', 'THIRD YEAR'), ('BY', 'BACHELOR YEAR')], default='FIRST YEAR', max_length=30),
        ),
    ]
