# Generated by Django 2.2.12 on 2021-04-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20210410_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentfeesdetail',
            old_name='branch_choose',
            new_name='branch',
        ),
    ]
