# Generated by Django 3.2 on 2021-04-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20210410_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeesdetail',
            name='branch',
            field=models.CharField(choices=[('Information Technology', 'Information Technology'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Computer Engineering', 'Computer Engineering'), ('Electronics Engineering', 'Electronics Engineering'), ('Aerospace Engineering', 'Aerospace Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineeing', 'Civil Engineeing')], default='Computer Engineering', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentfeesdetail',
            name='engineering_year',
            field=models.CharField(choices=[('FIRST YEAR', 'FIRST YEAR'), ('SECOND YEAR', 'SECOND YEAR'), ('THIRD YEAR', 'THIRD YEAR'), ('BACHELOR YEAR', 'BACHELOR YEAR')], default='FIRST YEAR', max_length=30),
        ),
    ]
